// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwapCheck.Infrastructure;

#nullable disable

namespace SwapCheck.Infrastructure.Migrations
{
    [DbContext(typeof(SwapCheckDbContext))]
    [Migration("20260509024010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SwapCheck.Domain.Entities.Engine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Aspiration")
                        .HasColumnType("int");

                    b.Property<int>("CylindersCount")
                        .HasColumnType("int");

                    b.Property<double>("Dimension")
                        .HasColumnType("float");

                    b.Property<double>("Displacement")
                        .HasColumnType("float");

                    b.Property<string>("EngineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineOrientation")
                        .HasColumnType("int");

                    b.Property<int>("EngineSize")
                        .HasColumnType("int");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlugAndPlay")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MountPattern")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresStandaloneECU")
                        .HasColumnType("bit");

                    b.Property<int>("Torque")
                        .HasColumnType("int");

                    b.Property<int>("TransBoltPattern")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("SwapCheck.Domain.Entities.SwapCompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("EngineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompatible")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.HasIndex("VehicleId");

                    b.ToTable("SwapCompatibilities");
                });

            modelBuilder.Entity("SwapCheck.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EngineSize")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MountPattern")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SwapCheck.Domain.Entities.SwapCompatibility", b =>
                {
                    b.HasOne("SwapCheck.Domain.Entities.Engine", "Engine")
                        .WithMany("SwapCompatibilities")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwapCheck.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("SwapCompatibilities")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SwapCheck.Domain.Entities.Engine", b =>
                {
                    b.Navigation("SwapCompatibilities");
                });

            modelBuilder.Entity("SwapCheck.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("SwapCompatibilities");
                });
#pragma warning restore 612, 618
        }
    }
}
